[project]
name = "crew_older"
version = "0.1.0"
description = "crew_older using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.18,<2.0.0"
]

[project.scripts]
crew_older = "crew_older.main:run"
run_crew = "crew_older.main:run"
train = "crew_older.main:train"
replay = "crew_older.main:replay"
test = "crew_older.main:test"
run_with_trigger = "crew_older.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "251d4b39-4ead-4e08-a3df-33b310a07a8f"
